-- TODO 5b: Crie a migration para a tabela employees.
--
-- Esta migration deve criar a tabela "employees" com as colunas:
-- - id BIGSERIAL PRIMARY KEY
-- - name VARCHAR(100) NOT NULL
-- - email VARCHAR(150) NOT NULL UNIQUE
-- - cpf VARCHAR(14) NOT NULL
-- - salary NUMERIC(10, 2) NOT NULL
-- - department_id BIGINT (FK para departments)
-- - created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- - updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
--
-- Exemplo:
--
-- CREATE TABLE employees (
--     id BIGSERIAL PRIMARY KEY,
--     name VARCHAR(100) NOT NULL,
--     email VARCHAR(150) NOT NULL UNIQUE,
--     cpf VARCHAR(14) NOT NULL,
--     salary NUMERIC(10, 2) NOT NULL,
--     department_id BIGINT,
--     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     CONSTRAINT fk_employee_department FOREIGN KEY (department_id) REFERENCES departments(id)
-- );
